# Generated by Django 3.1.4 on 2022-07-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220708_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(blank=True, choices=[('colombia', 'Colombia ')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='ProfileUser',
        ),
    ]
