# Generated by Django 3.1.4 on 2022-08-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_shippingaddress_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='editorials',
            name='name',
            field=models.CharField(blank=True, choices=[('norma', 'Norma'), ('ivrea', 'Ivrea'), ('dolmen', 'Dolmen'), ('kamite', 'Kamite'), ('panini', 'Panini'), ('ecc ediciones', 'ECC Ediciones')], max_length=200, null=True),
        ),
    ]
