products = [
    {
        '_id': 90,
        'name': "My Dress-Up Darling, Vol.1",
        'image': "/images/sono.jpg",
        'brand': "Editorial Panini",
        'category': "Shounen",
        'description':
        "Traumatizado por un incidente de la infancia con un amigo que se opuso a su amor por las muñecas tradicionales, el aspirante a la muñeca artesanal Wakana Gojo pasa sus días como solitario, encontrando consuelo en la habitación de su escuela secundaria. Para Wakana, personas como la hermosa Marin Kitagawa, una chica de moda que siempre está rodeada de una multitud de amigos, es prácticamente una alienígena de otro mundo. Pero cuando la alegre Marin, que nunca es tímida, ve a Wakana cosiendo un día después de la escuela, irrumpe con el objetivo de convertir a su tranquila compañera de clase en su pasatiempo secreto: ¡el cosplay! ¡¿Podrá el corazón herido de Wakana manejar la invasión de este sexy alienígena?!",
        'rating': "3.50",
        'numReviews': 2,
        'price': "12.00",
        'countInStock': 7,
        'createdAt': "2022-06-08T06:08:42.707298Z",
        'user': 1,
    },
    {
        '_id': 89,
        'name': "Kaguya-sama: Love Is War, Vol. 1",
        'image': "/images/kaguya.jpg",
        'brand': "Editorial Panin",
        'category': "Shounen",
        'description':
        "Dos genios de la escuela secundaria planean que el otro confiese su amor primero.\n\nDos genios. Dos cerebros. Dos corazones. Una batalla. ¿Quién confesará su amor primero...?!\n\n¡Como líderes del consejo estudiantil de su prestigiosa academia, Kaguya y Miyuki son la élite de la élite! Pero es solitario en la cima ... ¡Por suerte para ellos, se han enamorado! Solo hay un problema: ambos tienen demasiado orgullo para admitirlo. Y así comienza la intriga diaria para conseguir que el objeto de su afecto confiese primero sus sentimientos románticos...\n\nEl amor es una guerra que se gana perdiendo.",
        'rating': null,
        'numReviews': 0,
        'price': "6.00",
        'countInStock': 15,
        'createdAt': "2022-06-08T06:07:35.015396Z",
        'user': 1,
    },
    {
        '_id': 88,
        'name': "Spy x Family, Vol. 1",
        'image': "/images/spy.webp",
        'brand': "Ivrea",
        'category': "Shounen",
        'description':
        "¡Una comedia llena de acción sobre una familia falsa que incluye un espía, un asesino y un telépata!\n\nEl espía maestro Crepúsculo no tiene paralelo cuando se trata de ir encubierto en misiones peligrosas para el mejoramiento del mundo. Pero cuando recibe la asignación definitiva, casarse y tener un hijo, ¡finalmente puede estar por encima de su cabeza!\n\nTwilight, que no depende de los demás, tiene su trabajo hecho para él adquiriendo una esposa y un hijo para su misión de infiltrarse en una escuela privada de élite. ¡Lo que no sabe es que la esposa que ha elegido es una asesina y el niño que ha adoptado",
        'rating': "4.50",
        'numReviews': 2,
        'price': "9.50",
        'countInStock': 17,
        'createdAt': "2022-06-08T06:05:50.949569Z",
        'user': 1,
    },
    {
        '_id': 87,
        'reviews': [],
        'name': "Gleipnir Vol. 1",
        'image': "/images/gleipnir.jpg",
        'brand': "Kamite",
        'category': "Shounen",
        'description':
        "¡Un manga de acción de terror corporal oscuro y sexy perfecto para los fanáticos de Prison School y High School of the Dead! Shuichi Kagaya, un niño ordinario de secundaria en un pequeño pueblo aburrido. Pero cuando un hermoso compañero de clase se ve atrapado en un incendio en un almacén, descubre un poder misterioso: puede transformarse en un perro peludo con un revólver de gran tamaño y una cremallera en la espalda. Él salva la vida de la niña, compartiendo su secreto con ella. Pero está buscando a la hermana que mató a su familia, y no le importa lo degradante que se vuelva: usará a Shuichi para cumplir su misión ...",
        'rating': null,
        'numReviews': 0,
        'price': "3.60",
        'countInStock': 6,
        'createdAt': "2022-06-08T06:03:49.749648Z",
        'user': 1,
    },
    {
        '_id': 86,
        'name': "Ao-chan Can’t Study!, Vol. 1",
        'image': "/images/aochan.jpg",
        'brand': "Ivrea",
        'category': "Shounen",
        'description':
        'Cuando Ao estaba en el jardín de infantes, sonrió de oreja a oreja mientras les contaba a sus compañeros de clase cómo su padre, un autor erótico de gran éxito, eligió su nombre: "¡A como en la manzana y O como en la orgía!" Ese día todavía la persigue diez años después, ya que estudia con un solo objetivo en mente: ingresar a una universidad de élite y lograr la independencia de su padre de una vez por todas. No tiene juventud que perder y no tiene tiempo para pensar en los chicos... hasta que su compañero de clase, "King Normie" Kijima, se acerca a ella con una impactante confesión de amor. Ella intenta perder a Kijima, pero él simplemente no puede dar una pista ... y mientras su mente se vuelve loca con pensamientos sucios, ¡se da cuenta de que su padre la ha influenciado totalmente!',
        'rating': "5.00",
        'numReviews': 1,
        'price': "10.00",
        'countInStock': 3,
        'createdAt': "2022-06-08T06:01:27.683089Z",
        'user': 1,
    },
    {
        '_id': 85,
        'name': "Magical Sempai Vol. 1",
        'image': "/images/tejina.jpg",
        'brand': "Kamite",
        'category': "Shounen",
        'description':
        "\"La encontré ... un sempai lindo, pero 'extraño'!\" Esta sempai amante de la magia pero con miedo escénico con una tasa de fracaso del 100% a veces es linda y a veces erótica, por lo que no puedes quitarle los ojos de encima. ¡El cómic gag corto y mágico que ha causado un alboroto por todas partes con su puro humor ahora está en forma recopilada! ¡¡Nace la heroína no atlética definitiva!!",
        'rating': null,
        'numReviews': 0,
        'price': "3.40",
        'countInStock': 4,
        'createdAt': "2022-06-08T06:00:15.061747Z",
        'user': 1,
    },
    {
        '_id': 84,
        'name': "Mieruko-chan, Vol. 1",
        'image': "/images/mieruko_9bJzVK3.jpg",
        'brand': "Ivrea",
        'category': "Shounen",
        'description':
        "Una chica normal vivía una vida normal, hasta que no lo estaba.\nUn día, ella pudo ver ... todo. ¿Qué debe hacer una chica cuando aparecen monstruos horribles sin importar en qué dirección se dirija?\nY además de eso, ¡nadie más puede verlos! Obviamente, solo hay una cosa que tiene sentido: ignorarlos.\nSin embargo, es un poco difícil poner la teoría en práctica, cuando los fantasmas saben que ella está mirando ...",
        'rating': "5.00",
        'numReviews': 1,
        'price': "7.00",
        'countInStock': 10,
        'createdAt': "2022-06-08T05:55:20.189004Z",
        'user': 1,
    },
    {
        '_id': 83,
        'name': "Go Toubun no Hanayome, Vol.1",
        'image': "/images/gotobun.jpg",
        'brand': "Editorial Panini",
        'category': "Shounen",
        'description':
        "Fuutarou Uesugi es un estudiante de preparatoria que ha obtenido unas excelentes calificaciones, pero lleva una vida difícil a comparación de los demás: no tiene madre, no tiene ningún amigo y su padre tiene muchas deudas económicas, por lo que Fuutarou y su hermana menor, Raiha, a menudo pasan hambre.\n\nSe presenta una oportunidad cuando una familia rica llega a su escuela y Fuutarou es contratado como tutor altamente remunerado, sin embargo descubre que quedaron a su cargo unas encantadoras hermanas quintillizas idénticas con personalidades variadas, teniendo algo en común; no poseen interés en el estudio, lo que conlleva a que tengan unas malas calificaciones. Algunas de las quintillizas están en contra que Fuutarou sea su tutor, sin embargo su tenacidad diligente convence gradualmente a cada una de las chicas para que avancen en sus estudios.",
        'rating': "4.00",
        'numReviews': 1,
        'price': "4.00",
        'countInStock': 5,
        'createdAt': "2022-06-08T05:53:11.274331Z",
        'user': 1,
    },
]
